#GET
LIST_ENDPOINT = "list_endpoint"

# body val (POST/PUT)
TYPE_MISMATCH = "type_mismatch"
MISSING_REQUIRED = "missing_required"
BOUNDARY_NUMERIC = "boundary_numeric"
BOUNDARY_STRING = "boundary_string"
INVALID_ENUM = "invalid_enum"
INVALID_BOOLEAN = "invalid_boolean"
INVALID_PATTERN = "invalid_pattern"
NEGATIVE_VALUE = "negative_value"
VALID_DATA = "valid_data"
RESPONSE_SCHEMA_MISMATCH = "response_schema_mismatch"
MISSING_REQUIRED_QUERY_PARAM = "missing_required_query_param"
MALFORMED_JSON = "malformed_json"
WRONG_CONTENT_TYPE = "wrong_content_type"
METHOD_NOT_ALLOWED = "method_not_allowed"
#path params
VALID_ID = "valid_id"
NONEXISTENT_ID = "nonexistent_id"
INVALID_ID_FORMAT = "invalid_id_format"
NEGATIVE_ID = "negative_id"
INVALID_ARRAY_ITEM_TYPE = "invalid_array_item_type"
ARRAY_BOUNDARY = "array_boundary"
DUPLICATE_ARRAY_ITEMS = "duplicate_array_items"
NESTED_TYPE_MISMATCH = "nested_type_mismatch"
